-- Script

CREATE TABLE TIPODESPESA (
 ID_TIPODESPESA INT NOT NULL IDENTITY,
 NOME_TIPODESPESA VARCHAR(20) NOT NULL ,
PRIMARY KEY(ID_TIPODESPESA)); 
GO

CREATE TABLE MEMBRO (
 ID_MEMBRO INT NOT NULL IDENTITY,
 NOME_MEMBRO VARCHAR(20) NOT NULL ,
 PAPEL_MEMBRO VARCHAR(10) NOT NULL ,
PRIMARY KEY(ID_MEMBRO)); 
GO

CREATE TABLE DESPESA (
 ID_DESPESA INT NOT NULL IDENTITY,
 TIPODESPESA_ID_TIPODESPESA INT NOT NULL ,
 MEMBRO_ID_MEMBRO INT NOT NULL ,
 DATA_DESPESA DATE NOT NULL ,
 VALOR_DESPESA NUMERIC(10,2) NOT NULL ,
 OBS_DESPESA VARCHAR(50) NOT NULL ,
PRIMARY KEY(ID_DESPESA) ,
 FOREIGN KEY(TIPODESPESA_ID_TIPODESPESA)
 REFERENCES TIPODESPESA(ID_TIPODESPESA),
 FOREIGN KEY(MEMBRO_ID_MEMBRO)
 REFERENCES MEMBRO(ID_MEMBRO)); 
 GO
 
CREATE INDEX DESPESA_FKIndex1 ON DESPESA (TIPODESPESA_ID_TIPODESPESA); 
GO

CREATE INDEX DESPESA_FKIndex2 ON DESPESA (MEMBRO_ID_MEMBRO); 
GO

CREATE INDEX IFK_TIPODESPESA_DESPESA ON DESPESA
(TIPODESPESA_ID_TIPODESPESA);
GO

CREATE INDEX IFK_MEMBRO_DESPESA ON DESPESA (MEMBRO_ID_MEMBRO); 
GO